services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP:-localhost}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    stdin_open: true
    tty: true
